config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/show'
  root 'pages#home'

  get 'user/:id', to: 'users#show', as: 'user'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :rooms do
    resources :messages
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div>
      <a class="navbar-brand" href="/">Chat</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="text-light" style="padding-top: 5px; padding-left: 5px">
            <%= "Logged as #{current_user.email}" %>
          </li>
          <li class="nav-item">
            <%= link_to "Start Chatting", rooms_path, method: :get, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Account", edit_user_registration_path, method: :get, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-dark" %>
          </li>
        <% else %>
          <%= link_to "Login", new_user_session_path, method: :get, class: "nav-link active" %>
          <%= link_to "Sign up", new_user_registration_path, method: :get, class: "nav-link active" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@single_room, @message],
               remote: true,
               class: "d-flex",
               data: {
                controller: "reset-form",
                action: "turbo:submit-end->reset-form#reset"
              }) do |f| %>
    <%= f.text_field :body, id: 'chat-text', class: 'form-control msg-content', autocomplete: 'off' %>
    <%= f.submit data: { disable_with: false }, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room,
              remote: true,
              class: 'd-flex',
              data: {
                controller: "reset-form",
                action: "turbo:submit-end->reset-form#reset"
              }) do |f| %>
  <%= f.text_field :name, class: 'form-control', autocomplete: 'off' %>
  <%= f.submit data: { disable_with: false } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous" as="style" rel="stylesheet preload prefetch" >
    <style>
      <% if current_user %>
        <%= ".msg-#{current_user.id}" %>{
          background-color: #007bff !important;
          padding: 10px;
        } 
        <%= ".cont-#{current_user.id}" %>{
          display: flex;
        justify-content: flex-end;
        } 
      <% end %>
    </style>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>